<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AbLib>Mesh</AbLib><AbMd5Shim>true</AbMd5Shim></PropertyGroup>
  <Import Project="../ArenaBuilder.Lib.props" />
  <ItemGroup>
    <ProjectReference Include="../ArenaBuilder.Core/ArenaBuilder.Core.csproj" />
    <ProjectReference Include="../ArenaBuilder.Glb/ArenaBuilder.Glb.csproj" />
  </ItemGroup>
</Project>
